apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template
spec:
  params:
    - name: apikey
      description: the ibmcloud api key
    - name: branch
      default: master
    - name: triggerEvent
    # - name: clusterName
    #   description: the name of the cluster to target
    # - name: clusterTargetNamespace
    #   default: prod-tkn
    - name: app-name
    - name: image-name
    - name: registry-region-id
    - name: registry-namespace
    - name: chart-root
      default: chart
  resourcetemplates:
    # CD secret to provide API_KEY to access toolchain information
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    # - apiVersion: tekton.dev/v1alpha1
    #   kind: PipelineResource
    #   metadata:
    #     name: dev-cluster
    #   spec:
    #     type: cluster
    #     params:
    #       - name: name
    #         value: $(params.clusterName)
    #       - name: username
    #         value: norealvalueneeded
    #       - name: url
    #         value: https://no.real.value.needed
    #       - name: token
    #         value: norealvalueneeded
    #       - name: cadata
    #         value: norealvalueneeded
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: $(params.branch)-$(params.triggerEvent)-$(uid)
      spec:
        pipelineRef:
          name: pipeline
        workspaces:
          - name: pipeline-artifacts
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: app-name
            value: $(params.app-name)
          - name: image-name
            value: $(params.image-name)
          - name: policy-name
            value: $(params.policy-name)
          - name: umbrella-repo-name
            value: $(params.umbrella-repo-name)
          - name: chart-root
            value: $(params.chart-root)
          - name: registry-region-id
            value: $(params.registry-region-id)
          - name: registry-namespace
            value: $(params.registry-namespace)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-manual
spec:
  params:
    - name: repository
      value: "$(params.repository)"
    - name: branch
      value: "$(params.branch)"
    - name: triggerEvent
      value: manual
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-gitlab-commit
spec:
  params:
    - name: repository
      value: "$(params.repository)" # "$(event.repository.url)"
    - name: revision
      value: "$(event.checkout_sha)" # "$(event.head_commit.id)"
    - name: branch
      value: "$(params.branch)" # value: "$(event.ref)"
    - name: triggerEvent
      value: "git-commit"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener-manual-run
spec:
  triggers:
    - binding:
        name: trigger-binding-manual
      template:
        name: trigger-template
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener-git-commit
spec:
  triggers:
    - binding:
        name: trigger-binding-github-commit
      template:
        name: trigger-template
