apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: repository
      description: the git repo
    - name: branch
      description: the branch for the git repo
    # - name: clusterTargetNamespace     
    - name: deployment-file
      description: the manifest for kube deployment
      default: deployment.yml
    - name: app-name
      description: the name of the app
    - name: policy-name
      description: the policy for publishing the app
    - name: umbrella-repo-name
      description: Umbrella repo name
    - name: chart-root
      value: Component chart root folder
    - name: registry-region-id
      description: Region for container registry service
    - name: registry-namespace
      description: the namespace in container registry
#  resources:
    # - name: target-cluster
    #   type: cluster
  workspaces:
    - name: pipeline-artifacts
  tasks:
    - name: read-toolchain
      taskRef:
        name: read-toolchain-properties-task
      workspaces:
        - name: artifacts
          workspace: pipeline-artifacts
    - name: clone-repo
      taskRef:
        name: beta-clone-repo-task
      runAfter: [read-toolchain]
      workspaces:
        - name: artifacts
          workspace: pipeline-artifacts
      params:
        - name: repository
          value: $(tasks.read-toolchain.results.repository)
        - name: branch
          value: $(params.branch)
        - name: ibmcloud-api
          value: $(tasks.read-toolchain.results.ibmcloud-api)
    - name: record-build
      runAfter: [clone-repo]
      taskRef:
        name: record-build-task
      workspaces:
        - name: artifacts
          workspace: pipeline-artifacts
      params:
        - name: app-name
          value: $(params.app-name)
        - name: toolchain-id
          value: $(tasks.read-toolchain.results.toolchain-id)
        - name: build-number
          value: $(tasks.read-toolchain.results.build-number)
        - name: repository
          value: $(tasks.clone-repo.results.git-repository)
        - name: branch
          value: $(tasks.clone-repo.results.git-branch)
        - name: commit-id
          value: $(tasks.clone-repo.results.git-commit)
        - name: ibmcloud-api
          value: $(tasks.read-toolchain.results.ibmcloud-api)
    - name: unit-test
      runAfter: [record-build]
      taskRef:
        name: unit-test-task
      workspaces:
        - name: artifacts
          workspace: pipeline-artifacts
    - name: record-unit-test-results
      runAfter: [unit-test]
      taskRef:
        name: record-test-results-task
      workspaces:
        - name: artifacts
          workspace: pipeline-artifacts
      params:
        - name: app-name
          value: $(params.app-name)
        - name: toolchain-id
          value: $(tasks.read-toolchain.results.toolchain-id)
        - name: build-number
          value: $(tasks.read-toolchain.results.build-number)
        - name: ibmcloud-api
          value: $(tasks.read-toolchain.results.ibmcloud-api)
        - name: test-status
          value: $(tasks.unit-test.results.test-status)
        - name: file-locations
          value: $(tasks.unit-test.results.file-locations)
        - name: test-types
          value: $(tasks.unit-test.results.test-types)
    - name: prepare-containerize
      runAfter: [record-unit-test-results]
      taskRef:
        name: prepare-build-task
      workspaces:
        - name: artifacts
          workspace: pipeline-artifacts
      params:
        - name: image-name
          value: $(params.app-name)
        - name: build-number
          value: $(tasks.read-toolchain.results.build-number)
        - name: git-repository
          value: $(tasks.clone-repo.results.git-repository)
        - name: git-branch
          value: $(tasks.clone-repo.results.git-branch)
        - name: git-commit
          value: $(tasks.clone-repo.results.git-commit)
        - name: registry-region-id
          value: $(params.registry-region-id)
        - name: registry-namespace
          value: $(params.registry-namespace)
    - name: containerize
      runAfter: [prepare-containerize]
      taskRef:
        name: beta-cr-build-task
      workspaces:
        - name: workspace
          workspace: pipeline-artifacts
      params:
        - name: ibmcloud-api
          value: $(tasks.read-toolchain.results.ibmcloud-api)
        - name: git-branch
          value: $(tasks.clone-repo.results.git-branch)
        - name: git-commit
          value: $(tasks.clone-repo.results.git-commit)
        - name: image-url
          value: $(tasks.prepare-containerize.results.image-url)
        - name: additional-tags
          value: $(tasks.prepare-containerize.results.image-tag)
    - name: check-vulnerabilities
      runAfter: [containerize]
      taskRef:
        name: beta-vulnerability-advisor-task
      workspaces:
        - name: workspace
          workspace: pipeline-artifacts
      params:
        - name: scan-report-file
          value: 'app-image-va-report.json'
        - name: image-url
          value: $(tasks.prepare-containerize.results.image-url)
        - name: image-digest
          value: $(tasks.containerize.results.image-digest)
        # - name: maxIteration
        #   value: '5'
        # - name: sleepTime
        #   value: '3'
        - name: fail-on-scanned-issues          
          value: 'false'
    - name: record-vulnerabilities
      runAfter: [check-vulnerabilities]
      taskRef:
        name: record-test-results-task
      workspaces:
        - name: artifacts
          workspace: pipeline-artifacts
      params:
        - name: app-name
          value: $(params.app-name)
        - name: toolchain-id
          value: $(tasks.read-toolchain.results.toolchain-id)
        - name: build-number
          value: $(tasks.read-toolchain.results.build-number)
        - name: ibmcloud-api
          value: $(tasks.read-toolchain.results.ibmcloud-api)
        - name: test-status
          value: $(tasks.unit-test.results.test-status)
        - name: file-locations
          value: 'app-image-va-report.json'
        - name: test-types
          value: 'vulnerabilityadvisor'
    - name: publish-component
      runAfter: [check-vulnerabilities]
      taskRef:
        name: publish-component-task
      workspaces:
        - name: artifacts
          workspace: pipeline-artifacts
      params:
        - name: policy-name
          value: $(params.policy-name)
        - name: umbrella-repo-name
          value: $(params.umbrella-repo-name)
        - name: chart-root
          value: $(params.chart-root)
        - name: app-name
          value: $(params.app-name)
        - name: toolchain-id
          value: $(tasks.read-toolchain.results.toolchain-id)
        - name: build-number
          value: $(tasks.read-toolchain.results.build-number)
        - name: git-repository
          value: $(tasks.clone-repo.results.git-repository)
        - name: git-branch
          value: $(tasks.clone-repo.results.git-branch)
        - name: git-commit
          value: $(tasks.clone-repo.results.git-commit)
        - name: git-user
          value: $(tasks.clone-repo.results.git-user)
        - name: git-token
          value: $(tasks.clone-repo.results.git-token)
        - name: registry-namespace
          value: $(params.registry-namespace)
        - name: registry-url
          value: $(tasks.prepare-containerize.results.registry-url)
        - name: image-tag
          value: $(tasks.prepare-containerize.results.image-tag)
        - name: toolchain-id
          value: $(tasks.read-toolchain.results.toolchain-id)
    #================================================      
    # - name: cluster-setup
    #   taskRef:
    #     name: fetch-iks-cluster-config
    #   params:
    #     - name: task-pvc
    #       value: $(params.pipeline-pvc)
    #     - name: clusterPipelineResourcesDirectoryFallback
    #       value: .tekton-clusters
    #     - name: clusterAndWorkerNodesJsonExport
    #       value: .tekton-clusters
    #   resources:          
    #     inputs:
    #       - name: cluster
    #         resource: target-cluster
    #     outputs:
    #       - name: cluster
    #         resource: target-cluster
    # - name: kubernetes-deployment-validation
    #   runAfter: [containerize]
    #   taskRef:
    #     name: validate-k8s-deployment-file
    #   params:
    #     - name: task-pvc
    #       value: $(params.pipeline-pvc)
    #     - name: deployment-file
    #       value: $(params.deployment-file)
    #   resources:          
    #     inputs:
    #       - name: image
    #         resource: app-image
    #         from:
    #           - containerize
    # - name: kubernetes-environment-check
    #   runAfter: [cluster-setup]
    #   taskRef:
    #     name: validate-k8s-environment
    #   params:
    #     - name: task-pvc
    #       value: $(params.pipeline-pvc)
    #     - name: task-pvc-mountpath
    #       value: /pipelinerun
    #     - name: clusterPipelineResourcesDirectory
    #       value: /pipelinerun/.tekton-clusters
    #     - name: namespace
    #       value: $(params.clusterTargetNamespace)
    #   resources:          
    #     inputs:
    #       - name: cluster
    #         resource: target-cluster
    #       - name: image
    #         resource: app-image
    #         from:
    #           - containerize
    # - name: kubectl-deployment
    #   runAfter: [kubernetes-environment-check, kubernetes-deployment-validation]
    #   taskRef:
    #     name: kubernetes-contextual-execution
    #   params:
    #     - name: task-pvc
    #       value: $(params.pipeline-pvc)
    #     - name: task-pvc-mountpath
    #       value: /pipelinerun
    #     - name: clusterPipelineResourcesDirectory
    #       value: /pipelinerun/.tekton-clusters
    #     - name: script
    #       value: |
    #         echo "DEPLOYING using manifest"
    #         CLUSTER_NAMESPACE=$(params.clusterTargetNamespace)
    #         set -x
    #         kubectl apply --namespace $CLUSTER_NAMESPACE -f $(params.deployment-file)
    #         set +x
    #         echo "=========================================================="
    #         DEPLOYMENT_DOC_INDEX=$(yq read --doc "*" --tojson $(params.deployment-file) | jq -r 'to_entries | .[] | select(.value.kind | ascii_downcase=="deployment") | .key')
    #         DEPLOYMENT_NAME=$(yq read --doc ${DEPLOYMENT_DOC_INDEX} $(params.deployment-file) metadata.name)
    #         echo -e "CHECKING deployment rollout of ${DEPLOYMENT_NAME}"
    #         echo ""
    #         set -x
    #         if kubectl rollout status deploy/${DEPLOYMENT_NAME} --watch=true --timeout=150s --namespace $CLUSTER_NAMESPACE; then
    #           STATUS="pass"
    #         else
    #           STATUS="fail"
    #         fi
    #         set +x
    #         if [ "$STATUS" == "fail" ]; then
    #           echo "DEPLOYMENT FAILED"
    #           exit 1
    #         fi
    #
    #         # Find the cluster information for ingress or workers public ip
    #         TARGET_CLUSTER=$( yq read $KUBECONFIG clusters[0].name | awk -F/ '{print $1}' )
    #
    #         SERVICE_NAME=$(kubectl get services --namespace ${CLUSTER_NAMESPACE} -o json | jq -r ' .items[] | select (.spec.selector.app=="'"${DEPLOYMENT_NAME}"'") | .metadata.name ')
    #         if [ "$SERVICE_NAME" ]; then
    #           PORT=$( kubectl get services --namespace ${CLUSTER_NAMESPACE} | grep ${SERVICE_NAME} | sed 's/.*:\([0-9]*\).*/\1/g' )
    #           IP_ADDR=$(jq -r '.[0].publicIP' /pipelinerun/.tekton-clusters/${TARGET_CLUSTER}/${TARGET_CLUSTER}-workers.json)
    #           echo -e "VIEW THE APPLICATION AT: http://${IP_ADDR}:${PORT}"
    #         else
    #           echo "No service found for $DEPLOYMENT_NAME"
    #         fi
    #   resources:          
    #     inputs:
    #       - name: cluster
    #         resource: target-cluster
    #         from:
    #           - cluster-setup
