apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: publish-component-task
spec:
  params:
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: continuous-delivery-context-secret
      description: name of the configmap containing the continuous delivery pipeline context secrets
      default: cd-secret
    - name: container-registry-apikey-secret-key
      description: field in the secret that contains the api key used to login to ibmcloud container registry
      default: 'API_KEY'
    - name: policy-name
      description: Policy name for DevOps Insights
    - name: umbrella-repo-name
      description: Umbrella repo name
    - name: chart-root
      value: Component chart root folder
    - name: app-name
      description: Application name
    - name: toolchain-id
      description: Toolchain service instance id
    - name: build-number
      description: Pipeline build number
    - name: git-repository
      description: The cloned repository
    - name: git-branch
      description: The active branch for the repository
    - name: git-commit
      description: The current commit id that was cloned
    - name: git-user
      description: The auth user that cloned the repository
    - name: git-token
      description: The auth token that cloned the repository
    - name: registry-url
      description: URL for container registry service
    - name: registry-namespace
      description: the namespace in container registry
    - name: toolchain-id
      description: Toolchain service instance id
    - name: image-tag
      description: The tag of the built image
  workspaces:
    - name: artifacts
      description: the artifacts folder for this task
      mountPath: /artifacts
  steps:
    - name: check-gate
      image: ibmcom/pipeline-base-image
      workingDir: /artifacts
      env:
        - name: IBM_CLOUD_API_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.continuous-delivery-context-secret)
              key: $(params.container-registry-apikey-secret-key)
        - name: POLICY_NAME
          value: $(params.policy-name)
        - name: APP_NAME
          value: $(params.app-name)
        - name: TOOLCHAIN_ID
          value: $(params.toolchain-id)  
        - name: SOURCE_BUILD_NUMBER
          value: $(params.build-number)
      script: |
          #!/bin/bash
          set -e -o pipefail
          #source ./build.properties
          export TOOLCHAIN_ID=${TOOLCHAIN_ID} # for doi plugin
          ##########################################################################
          # Setting HOME explicitly to have ibmcloud plugins available
          # doing the export rather than env definition is a workaround
          # until https://github.com/tektoncd/pipeline/issues/1836 is fixed
          export HOME="/root"
          ##########################################################################
          source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_publish_gate_component_helm_chart.sh")
      volumeMounts:
        - mountPath: /cd-config
          name: cd-config-volume
    - name: publish-component
      image: ibmcom/pipeline-base-image
      workingDir: /artifacts
      env:
        - name: IBM_CLOUD_API_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.continuous-delivery-context-secret)
              key: $(params.container-registry-apikey-secret-key)
        - name: UMBRELLA_REPO_NAME
          value: $(params.umbrella-repo-name)
        - name: CHART_ROOT
          value: $(params.chart-root)
        - name: GIT_URL
          value: $(params.git-repository)
        - name: GIT_BRANCH
          value: $(params.git-branch)
        - name: GIT_COMMIT
          value: $(params.git-commit)
        - name: GIT_USER
          value: $(params.git-user)
        - name: GIT_PASSWORD
          value: $(params.git-token)         
        - name: SOURCE_BUILD_NUMBER
          value: $(params.build-number)
        - name: PIPELINE_TOOLCHAIN_ID
          value: $(params.toolchain-id)
        - name: APP_NAME
          value: $(params.app-name)  
        - name: IMAGE_NAME
          value: $(params.app-name)
        - name: IMAGE_TAG
          value: $(params.image-tag)
        - name: REGISTRY_URL
          value: $(params.registry-url) 
        - name: REGISTRY_NAMESPACE
          value: $(params.registry-namespace) 
      script: |
          #!/bin/bash
          set -x
          set -e -o pipefail
          #source ./build.properties
          ##########################################################################
          # Setting HOME explicitly to have ibmcloud plugins available
          # doing the export rather than env definition is a workaround
          # until https://github.com/tektoncd/pipeline/issues/1836 is fixed
          export HOME="/root"
          ##########################################################################
          cp ../cd-config/toolchain.json ./_toolchain.json #script expecting classic toolchain.json
          SOURCE_GIT_PASSWORD=${GIT_PASSWORD}
          source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/publish_component_helm_chart.sh")
      volumeMounts:
        - mountPath: /cd-config
          name: cd-config-volume
  volumes:
    - name: cd-config-volume
      configMap:
        name: toolchain
        items:
        - key: toolchain.json
          path: toolchain.json

